#!/bin/bash
set -eux

unset GITLAB_SWAPPINESS GITLAB_SWAP GITLAB_PRIVATE_NETWORK GITLAB_PORT GITLAB_MEMORY GITLAB_HOSTNAME GITLAB_HOST GITLAB_CPUS GITLAB_CACHE_PRESSURE
unset SMB_USER SMB_PASS
unset APT_MIRROR
. ./setenvs-local.sh; set -eux
. ./setenvs.sh; set -eux

export GITLAB_CPUS=2  #1,2
export GITLAB_MEMORY=8192  # 1526,2289,8192

set +eux
